In [1]:
import numpy as np

In [2]:
# arange(15)表示生成从0—14的一个函数，类似python中的range(start,end, step) 包含前面参数不包含后面参数, step表示步长
a = np.arange(1,16).reshape((3, 5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
a1 = np.arange(1, 10, 3)
a1

array([1, 4, 7])

In [31]:
# shape:numpy中ndarray对象的属性，数组的形状 3行5列
a.shape

(3, 5)

In [24]:
# ndim:numpy中ndarray对象的属性, 数组的维度 2维
a.ndim

2

In [25]:
# size:numpy中ndarray对象的属性， 数组中元素的个数
a.size

15

In [26]:
# dtype:numpy中ndarray对象的属性，数组中元素的数据类型
a.dtype

dtype('int64')

In [14]:
# array create  array()函数
a = np.array([1, 2, 3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [15]:
a.dtype

dtype('int32')

In [18]:
b = np.array([(1, 2., 3), (4, 5., 6)])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [19]:
b.dtype

dtype('float64')

In [21]:
# 生成复数数组  complex
c = np.array([(1, 2.),(3., 4)], dtype='complex')
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [23]:
# 生成初始值为0的3行4列数组 类似的函数 np.ones((3, 4), dtype=np.int16)
np.zeros((3, 4), dtype='int16')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [26]:
np.empty((2, 4))

array([[1., 0., 2., 0.],
       [3., 0., 4., 0.]])

In [33]:
from numpy import pi
# 在0-2之间输出9个数
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [37]:
# 在[0, 2*pi]中显示100个数,其中[]表示闭区间
x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [38]:
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [40]:
d = np.arange(6)
d

array([0, 1, 2, 3, 4, 5])

In [42]:
e = d.reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
g = np.arange(10000).reshape(100, 100)
g

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [50]:
np.set_printoptions(threshold=1001) # 此方法是根据threshold值设置打印多少数据
print(g)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [59]:
# basic arithmetic operators create new array
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b


array([0, 1, 2, 3])

In [60]:
c = a - b
c

array([20, 29, 38, 47])

In [61]:
a**2

array([ 400,  900, 1600, 2500])

In [62]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [64]:
a <= 30

array([ True,  True, False, False])

In [65]:
# 矩阵乘法
A = np.array([(1, 1), (0, 1)])
B = np.array([(2, 0), (3, 4)])
A * B # 这种乘法是两个矩阵对应元素的乘积 [[1*2,1*0], [0*3,1*4]] 

array([[2, 0],
       [0, 4]])

In [66]:
A.dot(B) # 矩阵乘法的运算

array([[5, 4],
       [3, 4]])

In [67]:
A @ B # 矩阵乘法运算

array([[5, 4],
       [3, 4]])

In [69]:
# 操作两个字符相当类型的数据，一般会转换成更精确的类型
a = np.ones(3, dtype=np.int16)
b = np.linspace(0, 2*pi, 3)
a + b

array([1.        , 4.14159265, 7.28318531])

In [71]:
c = a + b
c.dtype.name

'float64'

In [72]:
c * 1j

array([0.+1.j        , 0.+4.14159265j, 0.+7.28318531j])

In [73]:
2.7 ** (c * 1j)

array([ 0.5459684 +0.83780577j, -0.56360601-0.82604374j,
        0.58099033+0.81391046j])

In [75]:
a = np.exp(c*1j)
a

array([ 0.54030231+0.84147098j, -0.54030231-0.84147098j,
        0.54030231+0.84147098j])

In [76]:
a.dtype

dtype('complex128')

In [77]:
# random()
a = np.random.random((2, 3))
a                

array([[0.76440584, 0.64577522, 0.99775479],
       [0.03586014, 0.60718445, 0.30039289]])

In [78]:
a.sum() # 所有元素的和

3.351373332005581

In [79]:
a.min()  # 最小值

0.03586013652507791

In [80]:
a.max()  # 最大值

0.9977547915871732

In [70]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
b.min(axis=0) # axis参数表示维度， axis=0 表示row，axis=1表示column

array([0, 1, 2, 3])

In [84]:
b.sum(axis=1)

array([ 6, 22, 38])

In [85]:
b.cumsum(axis=0)  # 累加 axis=0表示行的累加

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [87]:
a = np.arange(10) **3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [20]:
def f(x, y):
    return 10*x + y
# fromfunction()函数参数 f函数怎么运算的？？
a = np.fromfunction(f, (4, 5), dtype=np.int32) 
a

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]], dtype=int32)

In [14]:
a[0:5,0]

array([ 0, 10, 20, 30], dtype=int32)

In [18]:
# 多维度的数组slice
a[2, :]

array([20, 21, 22, 23, 24], dtype=int32)

In [16]:
a[-1]

array([30, 31, 32, 33, 34], dtype=int32)

In [22]:
a = np.arange(45).reshape(3, 5, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [28]:
a[0,0:4,0]

array([0, 3, 6, 9])

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [35]:
a.shape

(5,)

In [40]:
a = np.floor(10 * np.random.random((3,4)))
a

array([[2., 5., 3., 3.],
       [9., 0., 9., 0.],
       [4., 0., 7., 2.]])

In [41]:
a.ravel()

array([2., 5., 3., 3., 9., 0., 9., 0., 4., 0., 7., 2.])

In [42]:
# reshape() 这个接口是重新定义数组的维度，还有一个resize()接口，此接口也是更改数组维度，
# 区别是reshpe()生成一个新的数组，resize()是在原数组上更改
a.reshape(6, 2)

array([[2., 5.],
       [3., 3.],
       [9., 0.],
       [9., 0.],
       [4., 0.],
       [7., 2.]])

In [43]:
a.T

array([[2., 9., 4.],
       [5., 0., 0.],
       [3., 9., 7.],
       [3., 0., 2.]])

In [49]:
a = np.random.random((2, 2))
b = np.random.random((2, 2))
np.vstack((a,b))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [47]:
np.hstack((a, b))

array([[0.83018895, 0.18993498, 0.3771571 , 0.81970391],
       [0.46002458, 0.61758002, 0.06499341, 0.36759374]])

In [4]:
c = np.array([[[0, 1, 2],
               [10, 11, 12]], 
               [[100, 101, 102],
               [110, 111, 112]]])
c

array([[[  0,   1,   2],
        [ 10,  11,  12]],

       [[100, 101, 102],
        [110, 111, 112]]])

In [5]:
c.shape

(2, 2, 3)

In [6]:
c[1,...]

array([[100, 101, 102],
       [110, 111, 112]])

In [7]:
c[:,1,:]

array([[ 10,  11,  12],
       [110, 111, 112]])

In [8]:
c[...,1]

array([[  1,  11],
       [101, 111]])

In [13]:
# flat属性是将数组平铺遍历
for e in c.flat:
    print(e, end=',')

0,1,2,10,11,12,100,101,102,110,111,112,

In [14]:
# Splitting one array into several smaller ones
a = np.floor(10*np.random.random((2,12)))
a

array([[6., 3., 6., 0., 3., 1., 3., 2., 8., 2., 8., 9.],
       [0., 0., 0., 3., 0., 9., 2., 1., 7., 9., 3., 5.]])

In [15]:
np.hsplit(a, 3)

[array([[6., 3., 6., 0.],
        [0., 0., 0., 3.]]), array([[3., 1., 3., 2.],
        [0., 9., 2., 1.]]), array([[8., 2., 8., 9.],
        [7., 9., 3., 5.]])]

In [16]:
np.vsplit(a, 2)

[array([[6., 3., 6., 0., 3., 1., 3., 2., 8., 2., 8., 9.]]),
 array([[0., 0., 0., 3., 0., 9., 2., 1., 7., 9., 3., 5.]])]

In [17]:
a = {"John": 1, "likes": 2, "to": 3, "watch": 4, "movies": 5, "also":6, "football": 7, "games": 8, "Mary": 9, "too": 10}
a

{'John': 1,
 'likes': 2,
 'to': 3,
 'watch': 4,
 'movies': 5,
 'also': 6,
 'football': 7,
 'games': 8,
 'Mary': 9,
 'too': 10}

In [18]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
# 这里的赋值并没有生成新的对象，a和b的指针都是指向同一个对象
b = a
b is a

True

In [22]:
id(a)

4520949440

In [23]:
id(b)

4520949440

In [24]:
# view() 函数生成了一个新的对象，对象的数据是a的数据
c = a.view()
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
c is a

False

In [26]:
c.base is a

True

In [29]:
# view() 出来的对象 指向的数据都是同一个存储位置上的数据，所以一个数据改了，另一个对象的数据也就跟着改了
c[0,3] = 999
a

array([[  0,   1,   2, 999],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [30]:
c

array([[  0,   1,   2, 999],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [31]:
a[0, 1] = 888
c

array([[  0, 888,   2, 999],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [32]:
a

array([[  0, 888,   2, 999],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [33]:
# 这个slice赋值，也是a的一个view()
s = a[ : , 1:3]
s

array([[888,   2],
       [  5,   6],
       [  9,  10]])

In [36]:
# 
s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [37]:
a

array([[  0,  10,  10, 999],
       [  4,  10,  10,   7],
       [  8,  10,  10,  11]])

In [38]:
# deep copy a new array object with new data is
d = a.copy()
d

array([[  0,  10,  10, 999],
       [  4,  10,  10,   7],
       [  8,  10,  10,  11]])

In [44]:
d.shape = (2, 6)
d

array([[  0,  10,  10, 999,   4,  10],
       [ 10,   7,   8,  10,  10,  11]])

In [45]:
a

array([[  0,  10,  10, 999],
       [  4,  10,  10,   7],
       [  8,  10,  10,  11]])

In [46]:
# the memory of a can be released.
del a

In [47]:
a

NameError: name 'a' is not defined

In [48]:
# 向量积  a = [l, m, n] b = [o, p, q] 则 a × b = [mq-np, no-lq, lp-mo]
np.cross([1, 2, 0], [4, 5, 6])


array([12, -6, -3])

In [56]:
# 内积
np.dot(np.array([1,2,3,4]).reshape(2,2),np.array([4,5,6,7]).reshape(2,2))

array([[16, 19],
       [36, 43]])

In [63]:
# outer  第一个参数代表行，第二个参数代表列
np.outer(np.array([(1, 2, 3,1,2,3)]), np.array([(4, 5, 6)]))

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18],
       [ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [64]:
x1 = [[1,2],[3,4]]
x2 = [[1,1],[1,1]]
outer = np.outer(x1,x2)
outer

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [67]:
# svd分解
np.linalg.svd([(1,2),(4,5)])

(array([[-0.32453643, -0.9458732 ],
        [-0.9458732 ,  0.32453643]]),
 array([6.76782894, 0.44327362]),
 array([[-0.60699365, -0.79470668],
        [ 0.79470668, -0.60699365]]))

In [68]:
# 矩阵点积计算公式：两个矩阵对应位置元素乘积之和
np.vdot([(1,2,3),(4,5,6)],[(1,2,3),(4,5,6)])

91

In [86]:
np.any([[False,False],[True,False]],axis=1)

array([False,  True])

In [88]:
a = np.arange(12)**2
i = np.array([1,1,3,8,5])
i

array([1, 1, 3, 8, 5])

In [89]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [90]:
# slice取数组中的值时，index可以一个数组，返回值的shape和i的shape相同
a[i]

array([ 1,  1,  9, 64, 25])

In [91]:
# slice取数组中的值时，index可以一个数组，返回值的shape和i的shape相同
j = np.array([(3, 4),(9, 7)])
a[j]

array([[ 9, 16],
       [81, 49]])

In [93]:
palette = np.array( [ [0,0,0], 
                      [255,0,0],
                      [0,255,0],
                      [0,0,255],
                      [255,255,255] ] )
palette

array([[  0,   0,   0],
       [255,   0,   0],
       [  0, 255,   0],
       [  0,   0, 255],
       [255, 255, 255]])